[project]
name = "url-shortener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.1",
    "fastapi[standard]>=0.128.0",
    "hashids>=1.3.1",
    "ruff>=0.14.13",
    "sqlalchemy>=2.0.45",
]
